### ISSUE TITLE
Adapter geht nicht mehr mit JS Controller 5.x und NodeJS 18.x

### ISSUE THREAD

**Issue by rogni38** [daniel-2k/ioBroker.nanoleaf-lightpanels#115]
Seit dem Update auf besagten Controller als auch Node JS geht der Adapter nicht mehr. Anbei der Log aus IObroker:

- 2023-07-16 13:48:17.068  - [32minfo[39m: host.IOBroker-Neu instance system.adapter.nanoleaf-lightpanels.0 started with pid 32183
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: node:internal/modules/cjs/loader:1080
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   throw err;
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   ^
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Require stack:
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/main.js
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:922:27)
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:110:18)
2023-07-16 13:48:17.294  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js:63:25)
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19) {
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   requireStack: [
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js',
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/main.js'
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   ]
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: }
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Node.js v18.16.1
2023-07-16 13:48:17.295  - [31merror[39m: host.IOBroker-Neu instance system.adapter.nanoleaf-lightpanels.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-07-16 13:48:17.295  - [32minfo[39m: host.IOBroker-Neu Rebuild for adapter system.adapter.nanoleaf-lightpanels.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
2023-07-16 13:48:18.940  - [32minfo[39m: host.IOBroker-Neu instance system.adapter.nanoleaf-lightpanels.1 started with pid 32190
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: node:internal/modules/cjs/loader:1080
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   throw err;
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   ^
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Require stack:
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/main.js
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:922:27)
2023-07-16 13:48:19.146  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:110:18)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js:63:25)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19) {
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   requireStack: [
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/lib/utils.js',
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels/main.js'
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]:   ]
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: }
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu Caught by controller[0]: Node.js v18.16.1
2023-07-16 13:48:19.147  - [31merror[39m: host.IOBroker-Neu instance system.adapter.nanoleaf-lightpanels.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-07-16 13:48:19.147  - [32minfo[39m: host.IOBroker-Neu Rebuild for adapter system.adapter.nanoleaf-lightpanels.1 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
2023-07-16 13:49:00.012  - [32minfo[39m: hm-rpc.1 (32124) Scheduled restart.

**Comment by mcm1957** [comment]
siehe auch https://github.com/daniel-2k/ioBroker.nanoleaf-lightpanels/issues/114

**Comment by daniel-2k** [comment]
Issue is already handled in #114. Issue will be closed.
